# AUTOGENERATED! DO NOT EDIT! File to edit: dev/01.01.local.ipynb (unless otherwise specified).

__all__ = ['list_buckets', 'find_or_create_bucket', 'remove_bucket', 'find_items', 'put', 'get', 'remove']

# Cell
from ..imports import *

# Cell

def list_buckets(**kw):
    """List buckets, using the keywords to create a filter,
    limit, and order.

    For NOOP, provide a buckets key to get a test set back."""
    return kw.get('buckets', [])

def find_or_create_bucket(**kw):
    """Find or create a bucket, returning the bucket.
    Use the keywords to name the bucket.

    For NOOP, provide a bucket to get a test bucket back."""
    return kw.get('bucket')

def remove_bucket(**kw):
    """Find and remove a bucket, if found.
    Use the keywords to name the bucket.

    For NOOP, provide a bucket to get a test bucket back."""
    return kw.get('bucket')

def find_items(**kw):
    """Find items in a bucket, returning a list of items.
    Use the keywords to name the bucket as well as filter,
    limit, and order the items.

    For NOOP, provide an items key to get a test set back.
    """
    return kw.get('items', [])

def put(**kw):
    """Put an item in a bucket, returning the status and the item.

    For NOOP, provide an item key to get a test item back."""
    return kw.get('item')

def get(**kw):
    """Find an item in a bucket, returning the item if found.
    Use the keywords to name the bucket as well as filter or name
    the item.

    For NOOP, provide an item key to get a test item back."""
    return kw.get('item')

def remove(**kw):
    """Remove an item from a bucket, if found, returning a status.
    Use the keywords to name the bucket as well as filter or name
    the item.

    For NOOP, provide a status key to get a test status back."""
    return kw.get('status')