#AUTOGENERATED! DO NOT EDIT! File to edit: dev/01_validate.ipynb (unless otherwise specified).

__all__ = ['is_traditional_distribution', 'extract_values', 'validate_with_shapiro_wilk', 'validate_distribution',
           'DEFAULT_VALIDATION_SIZE']

#Cell
DEFAULT_VALIDATION_SIZE = 500

def is_traditional_distribution(o):
    """A 'traditional' distribution has an `rvs`
    method attached, a tool for extracting random
    variables. Check if this is the case."""
    return hasattr(o, 'rvs')

def extract_values(o, *a, **kw):
    """Create a simple interface for either
    a distribution (e.g. `o.rvs(**kw)`) or a
    function (`o(**kw)`, or just an array-like
    object. (`np.array(o)`)."""
    if is_traditional_distribution(o): return np.array(o.rvs(*a, **kw))
    if callable(o): return np.array(o(*a, **kw))
    return np.array(o)

def validate_with_shapiro_wilk(o, accept=0.05, **kw):
    """Validate with the Shapiro-Wilk test..."""
    kw = {**dict(size=DEFAULT_VALIDATION_SIZE), **kw}
    data = extract_values(o, **kw)
    w, p = stats.shapiro(data)
    if len(data) > 5000: return w <= 1 - accept
    return p <= 1 - accept

def validate_distribution(o, validator=validate_with_shapiro_wilk, **kw):
    """Validate a distribution generally, using Shapiro-Wilk as
    a default validation."""
    return validator(o, **kw)