# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"foo": "00_core.ipynb",
         "list_buckets": "01.01.local.ipynb",
         "find_or_create_bucket": "01.01.local.ipynb",
         "remove_bucket": "01.01.local.ipynb",
         "find_items": "01.01.local.ipynb",
         "put": "01.01.local.ipynb",
         "get": "01.01.local.ipynb",
         "remove": "01.01.local.ipynb",
         "is_traditional_distribution": "01_validate.ipynb",
         "extract_values": "01_validate.ipynb",
         "extract_test_values": "01_validate.ipynb",
         "DEFAULT_VALIDATION_SIZE": "01_validate.ipynb",
         "plot_qq": "01_validate.ipynb",
         "ideal_normal": "01_validate.ipynb",
         "plot_ditribution_vs_normal": "01_validate.ipynb",
         "validate_with_shapiro_wilk": "01_validate.ipynb",
         "validate_distribution": "01_validate.ipynb",
         "listify": "02.00.develop.utils.ipynb",
         "PASSING_STATUS": "02.00.develop.utils.ipynb",
         "FAILING_STATUS": "02.00.develop.utils.ipynb",
         "FormatValidation": "02.00.develop.utils.ipynb",
         "format_validation": "02.00.develop.utils.ipynb",
         "ValidateCode": "02.00.develop.utils.ipynb",
         "validate_code": "02.00.develop.utils.ipynb",
         "ValidateRecord": "02.00.develop.utils.ipynb",
         "validate_records": "02.00.develop.utils.ipynb",
         "store": "02.01.develop.treatments.ipynb",
         "start": "02.01.develop.treatments.ipynb",
         "increment_version": "02.00.develop.utils.ipynb",
         "string_version": "02.00.develop.utils.ipynb",
         "revise": "02.01.develop.treatments.ipynb",
         "serialize": "02_protocols.ipynb",
         "deserialize": "02_protocols.ipynb",
         "compress": "02_protocols.ipynb",
         "decompress": "02_protocols.ipynb",
         "to_dict": "02_protocols.ipynb",
         "DEFAULT_COMPRESSION": "02_protocols.ipynb",
         "COMPRESSION_LEVELS": "02_protocols.ipynb",
         "MessageBuilder": "02_protocols.ipynb",
         "subject_builder": "02_protocols.ipynb",
         "treatment_builder": "02_protocols.ipynb",
         "model_builder": "02_protocols.ipynb",
         "evaluation_builder": "02_protocols.ipynb",
         "expectation_builder": "02_protocols.ipynb",
         "invocation_builder": "02_protocols.ipynb"}

modules = ["core.py",
           "object_store/noop.py",
           "object_store/local.py",
           "simulate/distribution.py",
           "develop/utils.py",
           "develop/treatments.py",
           "train/protocols.py"]

doc_url = "https://davidrichards.github.io/lab/"

git_url = "https://github.com/davidrichards/lab/tree/master/"

def custom_doc_links(name): return None
