#AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"foo": "00_core.ipynb",
         "is_traditional_distribution": "01_validate.ipynb",
         "extract_values": "01_validate.ipynb",
         "extract_test_values": "01_validate.ipynb",
         "DEFAULT_VALIDATION_SIZE": "01_validate.ipynb",
         "plot_qq": "01_validate.ipynb",
         "ideal_normal": "01_validate.ipynb",
         "plot_ditribution_vs_normal": "01_validate.ipynb",
         "validate_with_shapiro_wilk": "01_validate.ipynb",
         "validate_distribution": "01_validate.ipynb",
         "check_raises": "02_test_functions.ipynb",
         "check_is_near": "02_test_functions.ipynb",
         "check_equals": "02_test_functions.ipynb",
         "artifact_storage": "03_loop.ipynb",
         "generic_runner": "03_loop.ipynb",
         "runner": "03_loop.ipynb",
         "train_loop": "03_loop.ipynb",
         "get_matches": "03_loop.ipynb",
         "get_nth_match": "03_loop.ipynb",
         "get_first_match": "03_loop.ipynb"}

modules = ["core.py",
           "simulate/distribution.py",
           "util/test_functions.py",
           "train/loop.py"]

git_url = "https://github.com/your_github_username/lab/tree/master/"

def custom_doc_links(name): return None