#AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"foo": "00_core.ipynb"}

modules = ["core.py"]

git_url = "https://github.com/your_github_username/lab/tree/master/"

def custom_doc_links(name): return None