#AUTOGENERATED! DO NOT EDIT! File to edit: dev/03_loop.ipynb (unless otherwise specified).

__all__ = ['artifact_storage', 'generic_runner', 'runner', 'train_loop']

#Cell
def artifact_storage(*a, **kw):
    """Infer how the user intends to store
    artifacts: models, versions, treatments,
    and evaluation results."""

    def noop(subject, treatment, model, result): pass
    return noop

def generic_runner(subject, treatment, *a, **kw):
    """Naive concept. I have something smarter
    running somewhere, but I'm not sure where it is."""
    storage = artifact_storage(*a, **kw)
    model = None
    result = treatment(subject)
    return storage(subject, treatment, model, result)

def runner(*a, **kw):
    """Infer the runner and its artifact storage."""
    return generic_runner

def train_loop(subjects, treatments, *a, **kw):
    """The main training loop."""

    fn = runner(*a, **kw)

    for subject in np.array(subjects):
        for treatment in np.array(treatments):
            fn(subject, treatment, *a, **kw)
