# AUTOGENERATED! DO NOT EDIT! File to edit: dev/04_object_store.ipynb (unless otherwise specified).

__all__ = ['get_config']

# Cell

def get_config(**kw):
    """Get the local configuration dictionary."""

    # TODO: Actually manage this in a safe way.

    return {}